org.gradle.jvmargs=-Xmx4G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.11
loader_version=0.18.4
java_version=21

mod_version=0.4.9
maven_group=bep
archives_base_name=bephax_addon

meteor_version=1.21.11-SNAPSHOT
baritone_version=1.21.11-SNAPSHOT
xaero_minimap_version=fabric-1.21.11-26.4.2
xaero_worldmap_version=fabric-1.21.11-1.45.0
xaeroplus_version=2.35.3+fabric-1.21.11
litematica_version=0.26.13
malilib_version=0.27.18

lambdaevents_version=2.4.2
caffeine_version=3.2.0
fabric_api_version=0.141.6+1.21.11
