package bep.hax;

import bep.hax.capes.CapeManager;
import bep.hax.commands.Chats2b2t;
import bep.hax.commands.ChestTrackerCommand;
import bep.hax.commands.Connections2b2t;
import bep.hax.commands.Coordinates;
import bep.hax.commands.Deaths2b2t;
import bep.hax.commands.EmoteCommand;
import bep.hax.commands.EnemyCommand;
import bep.hax.commands.FirstSeen2b2t;
import bep.hax.commands.IrcCommand;
import bep.hax.commands.IsBot2b2t;
import bep.hax.commands.Kills2b2t;
import bep.hax.commands.LastSeen2b2t;
import bep.hax.commands.Playtime2b2t;
import bep.hax.commands.SessionLimit2b2t;
import bep.hax.commands.SetClear;
import bep.hax.commands.SetInput;
import bep.hax.commands.SetOutput;
import bep.hax.commands.StashStatus;
import bep.hax.commands.Stats2b2t;
import bep.hax.commands.TopPlaytime2b2t;
import bep.hax.commands.WaypointFollowerCommand;
import bep.hax.commands.WordCount2b2t;
import bep.hax.config.BepConfig;
import bep.hax.emoji.EmojiChatHandler;
import bep.hax.hud.DimensionCoords;
import bep.hax.hud.DubCounterHud;
import bep.hax.hud.ElytraHelperHud;
import bep.hax.hud.EntityList;
import bep.hax.hud.ItemCounterHud;
import bep.hax.hud.MobInfo;
import bep.hax.hud.MovementStatusHud;
import bep.hax.hud.PrinterHud;
import bep.hax.hud.SpeedKMH;
import bep.hax.hud.TimerSpeedHud;
import bep.hax.managers.PacketManager;
import bep.hax.modules.AngleCalculator;
import bep.hax.modules.AntiSpawnSet;
import bep.hax.modules.Api2b2t;
import bep.hax.modules.AutoBreed;
import bep.hax.modules.AutoCraft;
import bep.hax.modules.AutoPortal;
import bep.hax.modules.AutoRegear;
import bep.hax.modules.AutoRespond;
import bep.hax.modules.AutoSmith;
import bep.hax.modules.BepMine;
import bep.hax.modules.CaveAirESP;
import bep.hax.modules.ContainerTooltips;
import bep.hax.modules.ControlFly;
import bep.hax.modules.DisconnectSound;
import bep.hax.modules.ElytraBounce;
import bep.hax.modules.ElytraRecast;
import bep.hax.modules.ElytraSwap;
import bep.hax.modules.EmoteWheel;
import bep.hax.modules.FlowESP;
import bep.hax.modules.GhostContainer;
import bep.hax.modules.GhostMode;
import bep.hax.modules.GrimAirPlace;
import bep.hax.modules.GrimEntityBoost;
import bep.hax.modules.GrimGlide;
import bep.hax.modules.GrimScaffold;
import bep.hax.modules.GrimShulkerLaunch;
import bep.hax.modules.InvFix2b2t;
import bep.hax.modules.ItemSearchBar;
import bep.hax.modules.KillEffects;
import bep.hax.modules.KitMaker;
import bep.hax.modules.LoreLocator;
import bep.hax.modules.MapDuplicator;
import bep.hax.modules.Miner;
import bep.hax.modules.NoHurtCam;
import bep.hax.modules.NoJumpDelay;
import bep.hax.modules.ODMob;
import bep.hax.modules.PearlLoader;
import bep.hax.modules.Phase;
import bep.hax.modules.Pitch40;
import bep.hax.modules.Printer;
import bep.hax.modules.Proximity;
import bep.hax.modules.Replenish;
import bep.hax.modules.RocketBoost;
import bep.hax.modules.RocketFly;
import bep.hax.modules.RotationDetector;
import bep.hax.modules.ShulkerOverviewModule;
import bep.hax.modules.SignRender;
import bep.hax.modules.StashFinder;
import bep.hax.modules.StashMover;
import bep.hax.modules.StashMoverSelectionHandler;
import bep.hax.modules.Stripper;
import bep.hax.modules.TrailFollower;
import bep.hax.modules.UnfocusedFpsLimiter;
import bep.hax.modules.VanityESP;
import bep.hax.modules.VisualRangeNotifier;
import bep.hax.modules.WaypointFollower;
import bep.hax.modules.WebChat;
import bep.hax.modules.WheelPicker;
import bep.hax.modules.YCam;
import bep.hax.modules.YawLock;
import bep.hax.modules.arealoader.AreaLoader;
import bep.hax.modules.chesttracker.ChestTrackerModule;
import bep.hax.modules.livemessage.LiveMessage;
import bep.hax.modules.macro.MacroPlayer;
import bep.hax.modules.macro.MacroRecorder;
import bep.hax.profile.BundledProfile;
import bep.hax.serverlist.ServerOrganizer;
import bep.hax.util.EnemyManager;
import bep.hax.util.prox.EmoteManager;
import meteordevelopment.meteorclient.MeteorClient;
import meteordevelopment.meteorclient.addons.GithubRepo;
import meteordevelopment.meteorclient.addons.MeteorAddon;
import meteordevelopment.meteorclient.commands.Commands;
import meteordevelopment.meteorclient.systems.Systems;
import meteordevelopment.meteorclient.systems.hud.Hud;
import meteordevelopment.meteorclient.systems.hud.HudGroup;
import meteordevelopment.meteorclient.systems.modules.Category;
import meteordevelopment.meteorclient.systems.modules.Modules;
import net.minecraft.world.item.Items;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Bep extends MeteorAddon {
    public static final Logger LOG = LoggerFactory.getLogger("BepHax");
    public static final Category CATEGORY = new Category("Bephax", Items.ENCHANTED_GOLDEN_APPLE.getDefaultInstance());
    public static final Category HUNT_CATEGORY = new Category("BepHunt", Items.COMPASS.getDefaultInstance());
    public static final HudGroup HUD_GROUP = new HudGroup("Bephax");
    private PacketManager packetManager;

    @Override
    public void onInitialize() {
        LOG.info("BEPHAX LOADING.");
        CapeManager.getInstance().initialize();
        Systems.add(new EnemyManager());
        Systems.add(new ServerOrganizer());
        StashMoverSelectionHandler.init();
        Hud.get().register(ItemCounterHud.INFO);
        Hud.get().register(PrinterHud.INFO);
        Hud.get().register(EntityList.INFO);
        Hud.get().register(DimensionCoords.INFO);
        Hud.get().register(SpeedKMH.INFO);
        Hud.get().register(DubCounterHud.INFO);
        Hud.get().register(MobInfo.INFO);
        Hud.get().register(MovementStatusHud.INFO);
        Hud.get().register(TimerSpeedHud.INFO);
        Hud.get().register(ElytraHelperHud.INFO);
        Modules.get().add(new AutoSmith());
        Modules.get().add(new BepMine());
        Modules.get().add(new Printer());
        Modules.get().add(new YawLock());
        Modules.get().add(new UnfocusedFpsLimiter());
        Modules.get().add(new ShulkerOverviewModule());
        Modules.get().add(new ItemSearchBar());
        Modules.get().add(new Phase());
        Modules.get().add(new PearlLoader());
        Modules.get().add(new SignRender());
        Modules.get().add(new WheelPicker());
        Modules.get().add(new NoHurtCam());
        Modules.get().add(new YCam());
        Modules.get().add(new ElytraSwap());
        Modules.get().add(new WebChat());
        Modules.get().add(new LiveMessage());
        Modules.get().add(new Miner());
        Modules.get().add(new Replenish());
        Modules.get().add(new GhostMode());
        Modules.get().add(new AutoBreed());
        Modules.get().add(new WaypointFollower());
        Modules.get().add(new AutoRegear());
        Modules.get().add(new StashMover());
        Modules.get().add(new KitMaker());
        Commands.add(new SetInput());
        Commands.add(new SetOutput());
        Commands.add(new StashStatus());
        Commands.add(new SetClear());
        Commands.add(new EnemyCommand());
        Modules.get().add(new KillEffects());
        Modules.get().add(new MapDuplicator());
        Modules.get().add(new ElytraBounce());
        Modules.get().add(new RocketFly());
        Modules.get().add(new RocketBoost());
        Modules.get().add(new ElytraRecast());
        Modules.get().add(new ControlFly());
        Modules.get().add(new NoJumpDelay());
        Modules.get().add(new AutoPortal());
        Modules.get().add(new ChestTrackerModule());
        Modules.get().add(new ContainerTooltips());
        Modules.get().add(new Pitch40());
        Modules.get().add(new GrimAirPlace());
        Modules.get().add(new GrimScaffold());
        Modules.get().add(new GrimGlide());
        Modules.get().add(new GrimEntityBoost());
        Modules.get().add(new GrimShulkerLaunch());
        Modules.get().add(new TrailFollower());
        Modules.get().add(new Stripper());
        Modules.get().add(new VanityESP());
        Modules.get().add(new FlowESP());
        Modules.get().add(new CaveAirESP());
        Modules.get().add(new RotationDetector());
        Modules.get().add(new ODMob());
        Modules.get().add(new AreaLoader());
        Commands.add(new Coordinates());
        Modules.get().add(new AutoCraft());
        Modules.get().add(new MacroRecorder());
        Modules.get().add(new MacroPlayer());
        Modules.get().add(new Api2b2t());
        Modules.get().add(new Proximity());
        Modules.get().add(new EmoteWheel());
        Commands.add(new FirstSeen2b2t());
        Commands.add(new LastSeen2b2t());
        Commands.add(new Playtime2b2t());
        Commands.add(new Stats2b2t());
        Commands.add(new Kills2b2t());
        Commands.add(new Deaths2b2t());
        Commands.add(new Chats2b2t());
        Commands.add(new Connections2b2t());
        Commands.add(new TopPlaytime2b2t());
        Commands.add(new SessionLimit2b2t());
        Commands.add(new WordCount2b2t());
        Commands.add(new IsBot2b2t());
        Commands.add(new ChestTrackerCommand());
        Commands.add(new WaypointFollowerCommand());
        Commands.add(new IrcCommand());
        Commands.add(new EmoteCommand());
        Modules.get().add(new LoreLocator());
        Modules.get().add(new DisconnectSound());
        Modules.get().add(new AutoRespond());
        Modules.get().add(new InvFix2b2t());
        Modules.get().add(new StashFinder());
        Modules.get().add(new VisualRangeNotifier());
        Modules.get().add(new AntiSpawnSet());
        Modules.get().add(new AngleCalculator());
        Modules.get().add(new GhostContainer());
        MeteorClient.EVENT_BUS.subscribe(EmojiChatHandler.INSTANCE);
        EmoteManager.init();
        this.packetManager = new PacketManager();
        BepConfig.initialize();
        BundledProfile.init();
        LOG.info("BEPHAX LOADED.");
    }

    @Override
    public void onRegisterCategories() {
        Modules.registerCategory(CATEGORY);
        Modules.registerCategory(HUNT_CATEGORY);
    }

    @Override
    public String getWebsite() {
        return "https://bep.dek.to";
    }

    @Override
    public String getPackage() {
        return "bep.hax";
    }

    @Override
    public GithubRepo getRepo() {
        return null;
    }
}
